CREATE TABLE `administrators` (
	`id` INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(64),
	`email` VARCHAR(64) UNIQUE NOT NULL,
	`password` CHAR(64) NOT NULL,
	`created` TIMESTAMP NULL DEFAULT NULL,
	`last_login` TIMESTAMP NULL DEFAULT NULL,
	`status` SMALLINT UNSIGNED DEFAULT 0
);
